### ISSUE TITLE
显示打开成功，但是实际上并没有成功

### ISSUE THREAD

**Issue by YeLei1998** [zouhy2001/School_VirusMark#1]
老师还是提醒我打卡，配置没问题

**Comment by zouhy2001** [comment]
因为这个系统他不会校验数据是否正确，比如我的示例程序的数据全是捏造的，但post上去，他一样会返回成功。
建议检查你的数据是否正确，另外调试阶段，查询是否打卡成功你可以去支付宝签到记录里面确认是否真的签到成功，以那边为准。
其次，我这个学校代码是根据我自己学校代码推测的就是招生的学校代码，目前只有我自己学校是无误的，其他的我没有数据测试。
方便的话可以，发送你的数据给我我来试试，以便更详细的排查问题。
你是我GitHub第一个提issues的人，激动！！！

**Comment by zouhy2001** [comment]
> 老师还是提醒我打卡，配置没问题
另外我最新加了一个verify的功能，目的是代替从支付宝查看打卡是否成功，望对你调试有所帮助，意外收获是，好像捏造的数据查询不到是否打卡成功，意想不到的功能。

**Comment by YeLei1998** [comment]
这有啥激动的，遇到问题，提出问题，解决问题，hhh,我把数据给你试试，加个好友吧，不想在issues 发送我的个人信息

**Comment by zouhy2001** [comment]
邮我zouhy2001@gmail.com就行

**Comment by YeLei1998** [comment]
行，我上完课发你，要上课了

**Comment by YeLei1998** [comment]
关键信息发你了
