### ISSUE TITLE
一直能正常打卡，直到2022-07-07提示数据错误 ，还能解决吗

### ISSUE THREAD

**Issue by Leopoldxxx** [zouhy2001/School_VirusMark#10]
日志:

START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5

Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB

Starting new HTTPS connection (1): fxgl.jx.edu.cn:443

https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0

https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153

https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0

https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555

Starting new HTTPS connection (1): fxgl.jx.edu.cn:443

https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0

https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153

https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0

https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555

数据错误

Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null

END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5

Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB

**Comment by zouhy2001** [comment]
> 日志:
> 
> START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> 
> Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> 
> Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> 
> https://fxgl.jx.edu.cn:443 "POST /4136010406/studentQd/saveStu HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/index HTTP/1.1" 404 555
> 
> Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> 
> https://fxgl.jx.edu.cn:443 "POST /4136010406/studentQd/studentIsQd HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4136010406/index HTTP/1.1" 404 555
> 
> 数据错误
> 
> Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> 
> END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> 
> Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB

有大致分析过他的认证,有用到身份证md5,以及最重要的token的生成算法未知,大概率是无解的.

**Comment by zouhy2001** [comment]
随便加个盐哈希都破解不出

**Comment by Leopoldxxx** [comment]
> 随便加个盐哈希都破解不出

那岂不是，现在github上面的支付宝打卡的代码都失效了？

**Comment by zouhy2001** [comment]
> > 随便加个盐哈希都破解不出
> 
> 那岂不是，现在github上面的支付宝打卡的代码都失效了？

.GitHub上的打卡原理都是利用了 原系统的认证漏洞即:已知学校和学号就可以直接登录,有极大的隐私安全问题,现已修复该漏洞,故全部失效.

**Comment by zouhy2001** [comment]
> 日志:
> 
> START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> 
> Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> 
> Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> 
> https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> 
> https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
> 
> Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> 
> https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> 
> https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
> 
> https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
> 
> 数据错误
> 
> Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> 
> END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> 
> Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB

已更新脚本 你试试看 学校代码06 你是唱航的啊

**Comment by Leopoldxxx** [comment]
> > 日志:
> > START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
> > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
> > 数据错误
> > Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> > END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB
> 
> 已更新脚本 你试试看 学校代码06 你是唱航的啊
是阿 安卓有推荐抓包的软件和方式吗

**Comment by Leopoldxxx** [comment]
> > 日志:
> > START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
> > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
> > https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
> > 数据错误
> > Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> > END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB
> 
> 已更新脚本 你试试看 学校代码06 你是唱航的啊

，抓包后的auth_token是一直有效的吗

**Comment by Be-Forever** [comment]
请问一下怎么抓取auth_token，手游模拟器抓小程序的包还是抓url的包

**Comment by zouhy2001** [comment]
> > > 日志:
> > > START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > > Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> > > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > > https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> > > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
> > > https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
> > > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > > https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> > > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
> > > https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
> > > 数据错误
> > > Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> > > END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > > Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB
> > 
> > 
> > 已更新脚本 你试试看 学校代码06 你是唱航的啊
> > 是阿 安卓有推荐抓包的软件和方式吗

会用fiddler最好 可以参考这篇[文章](https://blog.csdn.net/qq_41945871/article/details/120650546?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165789412716782388079794%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165789412716782388079794&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~baidu_landing_v2~default-1-120650546-null-null.142%5Ev32%5Edown_rank,185%5Ev2%5Econtrol&utm_term=fidder%20every&spm=1018.2226.3001.4187) 按照正常的打开小程序 就能找到 login相关的包 token在请求体里面

**Comment by Leopoldxxx** [comment]
> > > > 日志:
> > > > START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > > > Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
> > > > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > > > https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > > > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
> > > > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
> > > > https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
> > > > Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
> > > > https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
> > > > https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
> > > > https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
> > > > https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
> > > > 数据错误
> > > > Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
> > > > END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
> > > > Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB
> > > 
> > > 
> > > 已更新脚本 你试试看 学校代码06 你是唱航的啊
> > > 是阿 安卓有推荐抓包的软件和方式吗
> 
> 会用fiddler最好 可以参考这篇[文章](https://blog.csdn.net/qq_41945871/article/details/120650546?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165789412716782388079794%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165789412716782388079794&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~baidu_landing_v2~default-1-120650546-null-null.142%5Ev32%5Edown_rank,185%5Ev2%5Econtrol&utm_term=fidder%20every&spm=1018.2226.3001.4187) 按照正常的打开小程序 就能找到 login相关的包 token在请求体里面

token是一直有效吗？

**Comment by zouhy2001** [comment]
时效不确定发自我的 iPhone在 2022年7月16日，17:03，Leopoldxxx ***@***.***> 写道：﻿




日志:
START RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
Init Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Coldstart: 1174ms (PullCode: 154ms InitRuntime: 6ms InitFunction: 1014ms) Memory: 128MB MemUsage: 16.28MB
Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
https://fxgl.jx.edu.cn:443 "GET /??/public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=4C9BB109ADE3F7CAA0B66CFC69AE5330 HTTP/1.1" 404 153
https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/saveStu HTTP/1.1" 302 0
https://fxgl.jx.edu.cn:443 "GET /4??index HTTP/1.1" 404 555
Starting new HTTPS connection (1): fxgl.jx.edu.cn:443
https://fxgl.jx.edu.cn:443 "GET /4??public/homeQd?loginName=20***&loginType=0 HTTP/1.1" 302 0
https://fxgl.jx.edu.cn:443 "GET /4??/index;jsessionid=0F56DA19ADDDB7FA88F5BC93BDA9A87D HTTP/1.1" 404 153
https://fxgl.jx.edu.cn:443 "POST /4??/studentQd/studentIsQd HTTP/1.1" 302 0
https://fxgl.jx.edu.cn:443 "GET /4??/index HTTP/1.1" 404 555
数据错误
Response RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 RetMsg: null
END RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5
Report RequestId: 187f4238-5394-41bd-bdc8-4b7cbcfacad5 Duration: 379ms Memory: 128MB MemUsage: 17.14MB

已更新脚本 你试试看 学校代码06 你是唱航的啊
是阿 安卓有推荐抓包的软件和方式吗


会用fiddler最好 可以参考这篇文章 按照正常的打开小程序 就能找到 login相关的包 token在请求体里面

token是一直有效吗？

**Comment by Leopoldxxx** [comment]
> 获取token后，在本地可以执行，但在云函数会报错：START RequestId: 200b5c57-1ab2-46e8-9285-7d123ea6622b

Event RequestId: 200b5c57-1ab2-46e8-9285-7d123ea6622b

Starting new HTTPS connection (1): xyfyapi.jx.edu.cn:443

是云函数的地址被屏闭了吗

**Comment by zouhy2001** [comment]
不是 是服务器拒绝链接 你尝试频率太高了 打卡系统那个服务器很垃圾 中间间隔一会发自我的 iPhone在 2022年7月16日，21:08，Leopoldxxx ***@***.***> 写道：﻿

获取token后，在本地可以执行，但在云函数会报错：START RequestId: 200b5c57-1ab2-46e8-9285-7d123ea6622b

Event RequestId: 200b5c57-1ab2-46e8-9285-7d123ea6622b
Starting new HTTPS connection (1): xyfyapi.jx.edu.cn:443
是云函数的地址被屏闭了吗
