### ISSUE TITLE
默认设置

### ISSUE THREAD

**Issue by 1955782864** [zouhy2001/School_VirusMark#3]
默认是非毕业班，健康状态吧

**Comment by zouhy2001** [comment]
默认是健康状态,没有仔细看过post的参数,json里的sfby这个参数是 是否毕业的意思? 我不是毕业年级,我是直接抓的包,应该没有问题.

**Comment by 1955782864** [comment]
那要是毕业呢，我没仔细看代码，我只改了改参数

**Comment by zouhy2001** [comment]
> 那要是毕业呢，我没仔细看代码，我只改了改参数

按照 第32行的参数 "sfby": "1", "jkzk": "0", "jkzkxq": "", "sfgl": "1" 推测

我是非毕业年级 参数值为1 健康状态健康为0 是否隔离 他的值也为1 ,由此推测 毕业年级sfby参数应该为0

**Comment by 1955782864** [comment]
jkzkxq是啥😂，好的我现在才大一，昨天晚上要求搞这个，试了两个脚本，你这个可以用，非常感谢

**Comment by zouhy2001** [comment]
> jkzkxq是啥😂，好的我现在才大一，昨天晚上要求搞这个，试了两个脚本，你这个可以用，非常感谢

这些参数都是拼音首字母,jkzkxq应该是健康状况需求,应该就是你打卡时的填的那个备注,
这些参数名也不是我定的,我抓的平时正常打卡的包,这个脚本就是模拟了数据上报
然后,很高兴能够帮到你.

**Comment by 1955782864** [comment]
好的👌🏻

**Comment by 1955782864** [comment]
能加个好友吗啊，老哥

**Comment by zouhy2001** [comment]
> 能加个好友吗啊，老哥

感觉不太方便,你可以follow我,有问题给我发邮件

**Comment by 1955782864** [comment]
好的
