### ISSUE TITLE
能不能加入教工的

### ISSUE THREAD

**Issue by xcf13363175** [zouhy2001/School_VirusMark#4]
能不能加入教工的

**Comment by zouhy2001** [comment]
方便的话可以邮我你的学校和工号,我抓包试试zouhy2001@gmail.com

**Comment by zouhy2001** [comment]
> 能不能加入教工的

方便的话可以邮我你的学校和工号,我抓包试试zouhy2001@gmail.com 我对教工打卡能不能实现也挺感兴趣的😀

**Comment by xcf13363175** [comment]
已发

**Comment by zouhy2001** [comment]
> 已发

很抱歉现在才回复你,其实前几天我就试了试发现不行,一直没回复你,
但是刚刚我成功登录了,
发现是教师的打卡接口和学生有所不同,
今天你已经打完卡,我想凌晨按照你的历史记录打卡,抓包.你看看可以吗

**Comment by zouhy2001** [comment]
> 已发

好了接口已经猜出来了,稍后commit,感谢你的issue
![image](https://user-images.githubusercontent.com/57806936/145705006-ed3e9962-bc11-48a0-b475-87116fda012c.png)

**Comment by zouhy2001** [comment]
有效的话,请在此feedback,谢谢😀

**Comment by xcf13363175** [comment]
刚刚看到，今天已经打卡，明天反馈。thx

**Comment by xcf13363175** [comment]
打卡成功！感谢支持
