### ISSUE TITLE
教师查看谁没有签到

### ISSUE THREAD

**Issue by zhang180031** [zouhy2001/School_VirusMark#6]
教师查看谁没有签到，然后用机器人在群里提醒对应的人签到，

**Comment by zouhy2001** [comment]
> 教师查看谁没有签到，然后用机器人在群里提醒对应的人签到，

这个功能我已经有给我辅导员实现
![image](https://user-images.githubusercontent.com/57806936/150676420-1dc130fe-defc-421c-a2dc-5831706569e6.png)

**Comment by zhang180031** [comment]
可以给个源码吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6)






教师查看谁没有签到，然后用机器人在群里提醒对应的人签到，

这个功能我已经有给我辅导员实现


—
直接回复此邮件，在 GitHub 上查看或者取消订阅.
GitHub Mobile 上的分流通知IOS 系统或机器人. 
你收到了这是因为你是这个线程的作者。留言 ID ***@***.***与&gt;

**Comment by zouhy2001** [comment]
> 可以给个源码吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6) 教师查看谁没有签到，然后用机器人在群里提醒对应的人签到， 这个功能我已经有给我辅导员实现 — 直接回复此邮件，在 GitHub 上查看或者取消订阅. GitHub Mobile 上的分流通知IOS 系统或机器人. 你收到了这是因为你是这个线程的作者。留言 ID ***@***.***与&gt;

这几天如果有时间的话我会尽快开源,如果鸽了,可以踢踢我

**Comment by zhang180031** [comment]
好滴好滴，谢谢大佬！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6)





  
可以给个源码吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:35 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6) 教师查看谁没有签到，然后用机器人在群里提醒对应的人签到， 这个功能我已经有给我辅导员实现 — 直接回复此邮件，在 GitHub 上查看或者取消订阅. GitHub Mobile 上的分流通知IOS 系统或机器人. 你收到了这是因为你是这个线程的作者。留言 ID @.***与&gt;
  
这几天如果有时间的话我会尽快开源,如果鸽了,可以踢踢我
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zouhy2001** [comment]
> 好滴好滴，谢谢大佬！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6) 可以给个源码吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:35 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [zouhy2001/School_VirusMark] 教师查看谁没有签到 (Issue #6) 教师查看谁没有签到，然后用机器人在群里提醒对应的人签到， 这个功能我已经有给我辅导员实现 — 直接回复此邮件，在 GitHub 上查看或者取消订阅. GitHub Mobile 上的分流通知IOS 系统或机器人. 你收到了这是因为你是这个线程的作者。留言 ID @.***与&gt; 这几天如果有时间的话我会尽快开源,如果鸽了,可以踢踢我 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已更新
